name: Keep Render App Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (GitHub Actions limit)
  workflow_dispatch:  # Allows manual run

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Render App
        run: |
          curl --silent --show-error --fail https://web-scraping-lnik.onrender.com || echo "Ping failed"
